name: confined_python

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - ipywidgets
  - pytables
  - pip
  - pillow
  - tqdm
  - uncertainties
  - ffmpeg
  - sympy
  - uproot
